### ISSUE TITLE
Accessing state from backend

### ISSUE THREAD

**Issue by dre-bk201** [ferreira-tb/tauri-plugin-pinia#11]
Is there any way to access the pinia store from rust through commands?

**Comment by ferreira-tb** [comment]
Hi. Yeah, that's possible.

You can access it from any type that implements the [`Manager`](https://docs.rs/tauri/2.0.0-rc/tauri/trait.Manager.html#) trait (e.g. [`AppHandle`](https://docs.rs/tauri/2.0.0-rc/tauri/struct.AppHandle.html#), [`Window`](https://docs.rs/tauri/2.0.0-rc/tauri/window/struct.Window.html), [`WebviewWindow`](https://docs.rs/tauri/2.0.0-rc/tauri/window/struct.Window.html)). However, the [`ManagerExt`](https://docs.rs/tauri-plugin-pinia/latest/tauri_plugin_pinia/trait.ManagerExt.html) trait must be in scope. Here is an example:

```rust
use tauri_plugin_pinia::ManagerExt;

#[tauri::command]
pub async fn print_foo(app: AppHandle) {
  // “my-store” is the store id. The same value used when calling `defineStore` in the frontend.
  let _ = app.with_store("my-store", |store| {
    if let Some(foo) = store.get("foo") {
      println!("foo: {foo}");
    }

    Ok(())
  });
}
```

The methods available for the Store can be found [here](https://docs.rs/tauri-plugin-pinia/latest/tauri_plugin_pinia/struct.Store.html).

I'll work on improving the documentation, but if you have any other questions, feel free to ask.

**Comment by dre-bk201** [comment]
Thank you so much for such a detailed response and so quickly at that🙏
